import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DeadLast",
  description: "Generated by create next app",
  icons: {
    // เติม ?v=1 เข้าไปข้างหลังเพื่อล้าง Cache ของ Browser
    icon: '/images/cowboy.png?v=1',
    shortcut: '/images/cowboy.png?v=1',
    apple: '/images/cowboy.png?v=1',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
